name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Configure AWS credentials (assume role)
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        role-session-name: github-actions-session
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to S3 using AWS CLI
      run: |
        aws s3 sync ./build/ s3://${{ secrets.AWS_S3_BUCKET }} \
          --acl public-read \
          --follow-symlinks \
          --delete